os: Visual Studio 2015

platform:
  - x64

environment:
   nodejs_version: "7"

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install -g npm@4.6.1
  - npm install
  - ls -a node_modules/.bin
  - npm ls --depth 0
  - npm bin

build_script:
  - npm run eslint-check